name: XYC-Intake
version: ${project.version}
description: Provides integration between the Intake command framework and Spigot
author: Literallie
website: https://l1t.li/
load: STARTUP

main: li.l1t.common.IntakePlugin
